### ISSUE TITLE
Test suite fails

### ISSUE THREAD

**Issue by juliangruber** [felixge/node-gently#24]
On a fresh install:

```bash
julian@Julians-MBP node-gently % make test
node test/simple/test-gently.js
node:assert:122
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: '[Foo].bar()' == '[object Object].bar()'
    at testUnamedClass (/Users/julian/dev/juliangruber/node-gently/test/simple/test-gently.js:324:12)
    at _name (/Users/julian/dev/juliangruber/node-gently/test/simple/test-gently.js:325:5)
    at test (/Users/julian/dev/juliangruber/node-gently/test/simple/test-gently.js:8:3)
    at Object.<anonymous> (/Users/julian/dev/juliangruber/node-gently/test/simple/test-gently.js:305:1)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
    at Module.load (node:internal/modules/cjs/loader:971:32)
    at Function.Module._load (node:internal/modules/cjs/loader:812:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: '[Foo].bar()',
  expected: '[object Object].bar()',
  operator: '=='
}
make: *** [test] Error 1
julian@Julians-MBP node-gently % node -v
v15.9.0
```

**Comment by juliangruber** [comment]
The same happens with node 10 through 14
